package test;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.Test;

import java.sql.SQLException;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;

import db.DBConnection;
import db.ProductDB;
import model.Product;

public class IntegrationTest2 {

    private TestUtilitiesGenerateData testUtil;
    private ProductDB productDB;

    @BeforeEach
    public void setUp() throws SQLException {
        // Connect to DB
        DBConnection.getInstance().startTransaction();
        testUtil = new TestUtilitiesGenerateData();
        productDB = new ProductDB();

        // Clean DB before each test
        testUtil.cleanDB();
    }

    @AfterEach
    public void tearDown() throws SQLException {
        // Clean up DB after each test
        testUtil.cleanDB();
        DBConnection.getInstance().rollbackTransaction();
    }

    @Test
    public void testCreateProduct() throws SQLException {
        // Arrange
        Product newProduct = new Product(3, "Michael Jackson", "MusicProduct", 100);

        // Act
        Product createdProduct = productDB.addProduct(newProduct);

        // Assert
        assertNotNull(createdProduct, "Product returned from DB should not be null");
        assertTrue(createdProduct.getProductId() > 0, "Product ID should be generated by the database");
        assertEquals("Michael Jackson", createdProduct.getName());
        assertEquals("MusicProduct", createdProduct.getProductType());

        // Check if it is DB
        Product retrieved = productDB.findProductById(createdProduct.getProductId());
        assertNotNull(retrieved, "Product can be retrieved");
        assertEquals(createdProduct.getName(), retrieved.getName());
        assertEquals(createdProduct.getProductType(), retrieved.getProductType());
    }
}
